### PR TITLE
Email content prompts users to restage apps

### PR DESCRIPTION
**Pull request by fureigh**
Incorporates the content from https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-8154.

* [x] Verify that all looks correct.
* [x] Check whether it's 👌 to remove this much (or more) HTML cruft.
* [x] Update test(s).
  * [x] Add test for multiple app
* [x] Check whether adding `appNoun` to the `notifyEmail` struct requires any changes that haven't yet been addressed.

## Single app
image

## Multiple apps
image

### CODE REVIEW

**Comment by jcscottiii** [comment]
> Check whether adding appNoun to the notifyEmail struct requires any changes that haven't yet been addressed.
`appNoun` may need to be exported (aka public) for the template like the other variables. (Capitalize the first letter of a variable name on a struct exports it)

**Comment by jcscottiii** [comment]
also
> Check whether it's 👌 to remove this much (or more) HTML cruft.

You'll find out when you do:
> Verify that all looks correct.

**Comment by fureigh** [comment]
@jcscottiii 🤔 If I recall correctly from my days of writing HTML emails, there are some particularities drawn from implementation variations among email clients and differences from a normal browser (like how you have to use inline styles).

@rememberlenny, can you lend any context about the previous version of this template? Specifically, is it 👌 to proceed with slightly fewer tables, in the manner of lines 293–300?

**Comment by fureigh** [comment]
I went ahead with the fewer-tables approach.

As described in https://github.com/18F/cg-buildpack-notify/pull/7/commits/38c0482c18ab650f2d843df1618d493fc8f69a59, there's a little more HTML tweaking to do to get the `single app` test to pass. I have to run for the evening but will return to this between now and sprint review. (Not to [cookie lick](communitymgt.wikia.com/wiki/Cookie_Licking); if you're reading this in the meantime and feel so moved, you're welcome to pick up those changes.)

**Comment by fureigh** [comment]
@jcscottiii I'm stuck on getting the 'single app' test to pass — can you take a look when you get in?

The remaining differences are all whitespace (e.g., the number of spaces in an otherwise empty line).

For further information:
1. Run `go test`, then:
2. Run `diff -u testdata/mail/notify/single_app.html testdata/mail/notify/single_app.html.returned`.
3. Inspect the discrepancies.

Even experimentally copying `single_app.html.returned` over `single_app.html`, then running `go test` again, wouldn't make the test pass. I'd wonder whether the comparison in line 60 of `templates_test.go` is somehow causing trouble, but prior to this ticket the test passed, which suggests the test is working correctly.

I look forward to hearing your insights.

**Comment by jcscottiii** [comment]
@fureigh i added a note here on how to test this: https://github.com/18F/cg-buildpack-notify/pull/7/commits/9818fdefe9ddb86d23c7dcd4aeafcc4b23a69770

**Comment by jcscottiii** [comment]
@el-mapache @rememberlenny please take a look

**Comment by rememberlenny** [comment]
Question for the team.

Regarding the text reference to links: I have been using the [1], [2], [3] format _in_ the anchor tag. This was an unconscious design decision that is now in cg-uaa-extras and the original dashboard emails.

For now, I think it would be good to keep this consistent. If we think its worth changing later, lets discuss it and make a change.

**Comment by jcscottiii** [comment]
@rememberlenny done

**Pull request merged**
